version: 0.2

env:
  parameter-store:
    ECR_REPO_URL: /terraform/build/lakehouse/callminer_bulk_pipeline_ecr_repo_url

phases:
  pre_build:
    commands:
      - rm -f .python-version
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 669610644781.dkr.ecr.eu-west-1.amazonaws.com

  build:
    commands:
      - echo Building the lambda image
      - docker build --no-cache -t pythonbuild .
      - docker tag pythonbuild:latest $ECR_REPO_URL:$VERSION
      - echo Finished building lambda image

  post_build:
    commands:
      - echo Pushing lambda image to ECR Repository
      - docker push $ECR_REPO_URL:$VERSION
      - echo Finished build and push of lambda image
