# pull dependency image from build account, push to env

version: 0.2

env:
  parameter-store:
    CROSS_ACCOUNT_ROLE: /build/jenkins/crossaccount/${ACCOUNT}/rolearn
    CROSS_ACCOUNT_ID: /build/jenkins/crossaccount/${ACCOUNT}/accountid
    CROSS_EXTERNAL_ID: /build/jenkins/crossaccount/${ACCOUNT}/externalid
    BUILD_ECR_REPO_URL: /terraform/build/lakehouse/callminer_bulk_pipeline_ecr_repo_url

phases:
  pre_build:
    commands:
      - rm -f .python-version
      - echo Starting pull build image and push to account
      - echo Getting current account details...
      - aws sts get-caller-identity > build_acc_details.json
      - export BUILD_ACC_ID=$(cat build_acc_details.json | jq .Account -r)
      - echo Current account number is $BUILD_ACC_ID

      - echo Logging in to ECR for build account...
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin $BUILD_ACC_ID.dkr.ecr.eu-west-1.amazonaws.com

      - echo Pulling docker image...
      - docker pull $BUILD_ECR_REPO_URL:$VERSION

  build:
    commands:
      - echo Assuming cross account role...
      - chmod 777 ./assume_role.sh
      - ./assume_role.sh $CROSS_ACCOUNT_ROLE $CROSS_EXTERNAL_ID cross-account

      - echo Logging in to ECR for ${ENVIRONMENT}...
      - aws ecr get-login-password --region eu-west-1 --profile cross-account | docker login --username AWS --password-stdin $CROSS_ACCOUNT_ID.dkr.ecr.eu-west-1.amazonaws.com

      - echo Pulling ECR Repo URL from SSM param for ${ENVIRONMENT} environment...
      - export ENV_ECR_REPO_URL_SSM=/terraform/${ENVIRONMENT}/lakehouse/callminer_bulk_pipeline_ecr_repo_url
      - aws ssm get-parameter --region eu-west-1 --profile cross-account --name $ENV_ECR_REPO_URL_SSM > env_ecr_repo_url.json
      - export ENV_ECR_REPO_URL=$(cat env_ecr_repo_url.json | jq .Parameter.Value -r)
      - echo Tagging docker image with name for ${ENVIRONMENT} account...
      - docker tag $BUILD_ECR_REPO_URL:$VERSION "$ENV_ECR_REPO_URL:${VERSION}"
      - docker images

  post_build:
    commands:
      - echo Pushing image to ${ENVIRONMENT}...
      - docker push "$ENV_ECR_REPO_URL:${VERSION}"
      - echo Done
